//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodi
    {
        public Proizvodi()
        {
            this.IzlazStavkes = new HashSet<IzlazStavke>();
            this.NarudzbaStavkes = new HashSet<NarudzbaStavke>();
            this.Ocjenes = new HashSet<Ocjene>();
            this.UlazStavkes = new HashSet<UlazStavke>();
        }
    
        public int ProizvodID { get; set; }
        public string Naziv { get; set; }
        public string Sifra { get; set; }
        public decimal Cijena { get; set; }
        public int VrstaID { get; set; }
        public int JedinicaMjereID { get; set; }
        public byte[] Slika { get; set; }
        public byte[] SlikaThumb { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<IzlazStavke> IzlazStavkes { get; set; }
        public virtual JediniceMjere JediniceMjere { get; set; }
        public virtual ICollection<NarudzbaStavke> NarudzbaStavkes { get; set; }
        public virtual ICollection<Ocjene> Ocjenes { get; set; }
        public virtual VrsteProizvoda VrsteProizvoda { get; set; }
        public virtual ICollection<UlazStavke> UlazStavkes { get; set; }
    }
}
